/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { ProUser } from "./ProUser";
import { ProUserCountArgs } from "./ProUserCountArgs";
import { ProUserFindManyArgs } from "./ProUserFindManyArgs";
import { ProUserFindUniqueArgs } from "./ProUserFindUniqueArgs";
import { DeleteProUserArgs } from "./DeleteProUserArgs";
import { ProUserService } from "../proUser.service";
@graphql.Resolver(() => ProUser)
export class ProUserResolverBase {
  constructor(protected readonly service: ProUserService) {}

  async _proUsersMeta(
    @graphql.Args() args: ProUserCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [ProUser])
  async proUsers(
    @graphql.Args() args: ProUserFindManyArgs
  ): Promise<ProUser[]> {
    return this.service.proUsers(args);
  }

  @graphql.Query(() => ProUser, { nullable: true })
  async proUser(
    @graphql.Args() args: ProUserFindUniqueArgs
  ): Promise<ProUser | null> {
    const result = await this.service.proUser(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => ProUser)
  async deleteProUser(
    @graphql.Args() args: DeleteProUserArgs
  ): Promise<ProUser | null> {
    try {
      return await this.service.deleteProUser(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
